services:
  transcription-service:
    build: .
    container_name: labendoc-transcription
    ports:
      - "8000:8000"
    environment:
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-2000}
      
      # Authentication
      - API_TOKEN=${API_TOKEN:-lSaWtIgjLeWUWBA%FinQI0RgVFiZJtLE}
      
      # Service Configuration
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
      # FFmpeg Configuration
      - FFMPEG_BINARY=/usr/bin/ffmpeg
      - FFPROBE_BINARY=/usr/bin/ffprobe
      
      # Python Configuration
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', headers={'Authorization': 'Bearer lSaWtIgjLeWUWBA%FinQI0RgVFiZJtLE'})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - labendoc-network

networks:
  labendoc-network:
    driver: bridge 